### ISSUE TITLE
Why filters don't work ?

### ISSUE THREAD

**Issue by adioziaete** [detectibr/ThreatTrack#1]
Why filters don't work ?
![2](https://github.com/detectibr/ThreatTrack/assets/122085783/ada54104-ddae-471e-a721-8d6351a90f71)

**Comment by Ls4ss** [comment]
Hi, to concatenate filters, remember to use quotation marks, as referenced in the tool's help.
Hope this helps!

Below is the result of the command, and always invoke the CVE's ( --cve), before requesting the CVSS (--cvss:critical)

![image](https://github.com/Ls4ss/ThreatTrack/assets/25537761/18398831-e852-4f4e-a265-693f2662199c)

**Comment by Ls4ss** [comment]
Hi, to concatenate filters, remember to use quotation marks, as referenced in the tool's help.
Hope this helps!

Below is the result of the command

![image](https://github.com/Ls4ss/ThreatTrack/assets/25537761/0f72b793-5b82-499b-8b86-9cbda6aa8797)

Below is the result of the same filter directly on Shodan

![image](https://github.com/Ls4ss/ThreatTrack/assets/25537761/5dd4966f-5316-4435-a1df-39176d4394ca)
